# @package _group_

filters:
  "1":
    filter_name: voxelization
    voxel_size: 0.2

  "2":
    filter_name: to_tensor
    keys:
      voxel_means: input_data
      voxel_covariances: input_covariances
