# @package _group_

algorithm: "icp_F2M"
max_num_alignments: 10

data_key: numpy_pc # The pointcloud on which the ICP is performed

local_map: ??? # config of the local map
initialization: ??? # config of the initialization
alignment: ??? # config of the rigid alignment
